# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
dist: trusty
sudo: required
cache: packages
addons:
   apt:
     packages:
       - libgeos-dev
       - gdal-bin
       - libudunits2-dev
       - libproj-dev
       - libgdal-dev
       - libnetcdf-dev
       - netcdf-bin

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
